### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/ipfs-mans#1]
@Kubuxu I am so sorry, I have failed to keep the context for this in my head. I know that you were working on something; what are the next steps for this repository?

**Comment by Kubuxu** [comment]
- [x] - export go-ipfs
- [ ] - clean up add missing help text (`ipfs --help` is whole in the `Subcommands` section which wasn't exported)
- [ ] - introduce more argument and option types
- [ ] - talk with js what format they can accept (JSON schema wise)
- [ ] - js CLI works off this
- [ ] - transition go-ipfs to work off it

**Comment by RichardLitt** [comment]
Thanks, @diasdavid.

**Comment by Mr0grog** [comment]
@Kubuxu @RichardLitt is this repo still worth pursuing? There hasn’t been any work on it in a couple years, and it doesn’t seem like it ever got past having any more details than is/was already available through the CLI `--help` option.

This is on the deprecation list here: https://github.com/ipfs/docs/issues/54#issuecomment-386409096

**Comment by Mr0grog** [comment]
If no, then we should:

- Update the README
- Update the description
- Add the `deprecated` topic tag, and
- Archive it (unless we should really just delete the repo entirely)

I can update the README, but don’t have permissions to do the rest.

**Comment by RichardLitt** [comment]
Archive. 👍
